Repository mash-up-kr/gabbangzip-iOS, pull requests merged in 2024-06, with the labels that each got.

#26 [Infra] Privacy Manifest 파일 생성 및 적용
  Projects/App/Resources/PrivacyInfo.xcprivacy
Labels: Infra

#28 [Feat] ActivityView & 전체 및 부분 뷰 스냅샷 캡쳐 & Lottie 컴포넌트 & extension 기능 추가
  Projects/App/Sources/ContentView.swift
  Projects/Core/Common/Extensions/Array+extensions.swift
  Projects/Core/Common/Extensions/View+extensions.swift
  Projects/Core/Common/Views/ActivityView.swift
  Projects/Core/Project.swift
  Projects/Core/Services/SnapshotClient/SnapshotClient.swift
  Projects/DesignSystem/Project.swift
  Projects/DesignSystem/Resources/Dummy.swift
  Projects/DesignSystem/Resources/Lotties/bookmark.json
  Projects/DesignSystem/Resources/Lotties/confetti.json
  Projects/DesignSystem/Sources/Colors/Color+extensions.swift
  Projects/DesignSystem/Sources/Colors/UIColor+extensions.swift
  Projects/DesignSystem/Sources/Images/UIImage+extensions.swift
  Projects/DesignSystem/Sources/Views/LottieView.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+extensions.swift
  Workspace.swift
Labels: Feature

#32 [Feat] HapticClient 구현
  .swiftlint.yml
  Projects/Core/Services/Haptic/HapticClient.swift
Labels: Feature

#34 [Feat] AppDelegate 추가, AppDelegateReducer 구현 및 여러 Client들 구현
  Projects/App/Sources/AppDelegate.swift
  Projects/App/Sources/AppDelegateReducer.swift
  Projects/App/Sources/GabbangzipApp.swift
  Projects/Core/Services/Bundle/BundleClient.swift
  Projects/Core/Services/UserDefaults/UserDefaultsClient.swift
  Projects/Core/Services/UserNotifications/UserNotificationClient.swift
  Xcode Templates/Dependency.xctemplate/TemplateIcon-1016.png
  Xcode Templates/Dependency.xctemplate/TemplateIcon-1016@2x.png
  Xcode Templates/Dependency.xctemplate/TemplateInfo.plist
  Xcode Templates/Dependency.xctemplate/___FILEBASENAME___.swift
  Xcode Templates/Feature.xctemplate/TemplateIcon-1016.png
  Xcode Templates/Feature.xctemplate/TemplateIcon-1016@2x.png
  Xcode Templates/Feature.xctemplate/TemplateInfo.plist
  Xcode Templates/Feature.xctemplate/___FILEBASENAME___Core.swift
  Xcode Templates/Feature.xctemplate/___FILEBASENAME___View.swift
  Xcode Templates/Reducer.xctemplate/TemplateIcon-1016.png
  Xcode Templates/Reducer.xctemplate/TemplateIcon-1016@2x.png
  Xcode Templates/Reducer.xctemplate/TemplateInfo.plist
  Xcode Templates/Reducer.xctemplate/___FILEBASENAME___Core.swift
Labels: Feature

#36 [Feat] 사진 앨범 기능 및 사진 권한 확인/요청 서비스 객체 구현
  Projects/App/Info.plist
  Projects/Core/Services/Haptic/HapticClient.swift
  Projects/Core/Services/PhotoClient/PhotoClient.swift
  Projects/Core/Services/SnapshotClient/SnapshotClient.swift
  Projects/DesignSystem/Sources/Views/PhotoPicker/GabbangzipPhotoPicker.swift
  Projects/DesignSystem/Sources/Views/PhotoPicker/MaxSelectedCountType.swift
Labels: Feature

#40 [Feat] DebugLogger 구현
  Projects/Core/Common/Extensions/DateFormatter+extensions.swift
  Projects/Core/Common/Utilities/DebugLogger.swift
  Projects/Core/Common/Utilities/SwiftLog.swift
Labels: Feature

#55 [Chore] TCA 템플릿 보완
  Projects/Features/Scene/Project.swift
  Xcode Templates/Feature.xctemplate/___FILEBASENAME___Core.swift
  Xcode Templates/Feature.xctemplate/___FILEBASENAME___View.swift
  Xcode Templates/Reducer.xctemplate/___FILEBASENAME___Core.swift
Labels: Chore

#56 [Feat] KakaoClient 생성 및 AppReducer 생성
  .gitignore
  Projects/App/Info.plist
  Projects/App/Sources/AppDelegate.swift
  Projects/App/Sources/AppDelegateCore.swift
  Projects/App/Sources/ContentView.swift
  Projects/App/Sources/GabbangzipApp.swift
  Projects/App/Sources/RootCore.swift
  Projects/App/Sources/RootView.swift
  Projects/App/xcconfigs/Gabbangzip.debug.xcconfig
  Projects/App/xcconfigs/Gabbangzip.release.xcconfig
  Projects/App/xcconfigs/Gabbangzip.shared.xcconfig
  Projects/Core/Models/Kakao/KaKaoUserInformation.swift
  Projects/Core/Project.swift
  Projects/Core/Services/GetHelpers/NetworkManager.swift
  Projects/Core/Services/GetHelpers/RouteType.swift
  Projects/Core/Services/KakaoLogin/KakaoLoginClient.swift
  Projects/Core/Services/Photo/PhotoClient.swift
  Projects/Core/Services/Snapshot/SnapshotClient.swift
  Projects/Features/Coordinator/Project.swift
  Projects/Features/Scene/Project.swift
  Tuist/Package.resolved
  Tuist/Package.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+extensions.swift
Labels: Feature

#60 [Design] 뷰 컴포넌트 제작 및 아이콘 및 컬러 에셋 나머지 추가
  Projects/DesignSystem/Resources/Colors.xcassets/Category/ClassicRoseBackground.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Category/CoralBackground.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Category/GeraldineBackground.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Category/MalibuBackground.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Category/ManzBackground.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Category/MintGreenBackground.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Category/PerfumeBackground.colorset/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Category/club_active.imageset/club_active.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Category/club_inactive.imageset/club_inactive.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Category/community_active.imageset/community_active.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Category/community_inactive.imageset/community_inactive.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Category/company_active.imageset/company_active.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Category/company_inactive.imageset/company_inactive.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Category/exercise_active.imageset/exercise_active.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Category/exercise_inactive.imageset/exercise_inactive.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Category/gathering_active.imageset/gathering_active.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Category/gathering_inactive.imageset/gathering_inactive.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Category/hobby_active.imageset/hobby_active.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Category/hobby_inactive.imageset/hobby_inactive.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Category/school_Inactive.imageset/school_Inactive.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Category/school_active.imageset/school_active.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Category/school_inactive.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Category/school_inactive.imageset/school_inactive.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Common/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Common/calendar.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Common/calendar.imageset/calendar.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Common/copy.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Common/copy.imageset/copy.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Common/gallery.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Common/gallery.imageset/gallery.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Common/time.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Common/time.imageset/time.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Navigation/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Navigation/back.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Navigation/back.imageset/back.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Navigation/group.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Navigation/group.imageset/group.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Navigation/logo.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Navigation/logo.imageset/logo.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Navigation/notice.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Navigation/notice.imageset/notice.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Navigation/plus.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Navigation/plus.imageset/plus.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Navigation/user.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Navigation/user.imageset/user.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Popup/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Popup/popup_check.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Popup/popup_check.imageset/popup_check.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Popup/popup_info.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Popup/popup_info.imageset/popup_info.svg
  Projects/DesignSystem/Sources/Views/Button/KeywordButton.swift
  Projects/DesignSystem/Sources/Views/Button/SmallButton.swift
  Projects/DesignSystem/Sources/Views/Button/SmallPopupButton.swift
  Projects/DesignSystem/Sources/Views/Chip/SmallChip.swift
  Projects/DesignSystem/Sources/Views/Chip/Tag.swift
  Projects/DesignSystem/Sources/Views/Chip/Types/CategoryType.swift
  Projects/DesignSystem/Sources/Views/Chip/Types/EtcType.swift
  Projects/DesignSystem/Sources/Views/NavigationBar/NavigationBar.swift
  Projects/DesignSystem/Sources/Views/NavigationBar/Types/NavigationBarType.swift
  Projects/DesignSystem/Sources/Views/Toggle/GabbangzipToggle.swift
Labels: Design

#64 [Infra] 오픈소스 라이센스 정보 표시
  Projects/App/Resources/Settings.bundle/LicenseProject.latest_result.txt
  Projects/App/Resources/Settings.bundle/LicenseProject.plist
  Projects/App/Resources/Settings.bundle/LicenseProject/Alamofire.plist
  Projects/App/Resources/Settings.bundle/LicenseProject/FlowStacks.plist
  Projects/App/Resources/Settings.bundle/LicenseProject/Get.plist
  Projects/App/Resources/Settings.bundle/LicenseProject/MultipartFormDataKit.plist
  Projects/App/Resources/Settings.bundle/LicenseProject/Nuke.plist
  Projects/App/Resources/Settings.bundle/LicenseProject/TCACoordinators.plist
  Projects/App/Resources/Settings.bundle/LicenseProject/combine-schedulers.plist
  Projects/App/Resources/Settings.bundle/LicenseProject/kakao-ios-sdk.plist
  Projects/App/Resources/Settings.bundle/LicenseProject/lottie-ios.plist
  Projects/App/Resources/Settings.bundle/LicenseProject/swift-case-paths.plist
  Projects/App/Resources/Settings.bundle/LicenseProject/swift-clocks.plist
  Projects/App/Resources/Settings.bundle/LicenseProject/swift-collections.plist
  Projects/App/Resources/Settings.bundle/LicenseProject/swift-composable-architecture.plist
  Projects/App/Resources/Settings.bundle/LicenseProject/swift-concurrency-extras.plist
  Projects/App/Resources/Settings.bundle/LicenseProject/swift-custom-dump.plist
  Projects/App/Resources/Settings.bundle/LicenseProject/swift-dependencies.plist
  Projects/App/Resources/Settings.bundle/LicenseProject/swift-identified-collections.plist
  Projects/App/Resources/Settings.bundle/LicenseProject/swift-perception.plist
  Projects/App/Resources/Settings.bundle/LicenseProject/swift-syntax.plist
  Projects/App/Resources/Settings.bundle/LicenseProject/swiftui-navigation.plist
  Projects/App/Resources/Settings.bundle/LicenseProject/xctest-dynamic-overlay.plist
  Projects/App/Resources/Settings.bundle/Root.plist
  Projects/App/Settings.bundle/LicenseProject.latest_result.txt
  Projects/App/Settings.bundle/LicenseProject.plist
  Projects/App/Settings.bundle/LicenseProject/Alamofire.plist
  Projects/App/Settings.bundle/LicenseProject/FlowStacks.plist
  Projects/App/Settings.bundle/LicenseProject/Get.plist
  Projects/App/Settings.bundle/LicenseProject/MultipartFormDataKit.plist
  Projects/App/Settings.bundle/LicenseProject/Nuke.plist
  Projects/App/Settings.bundle/LicenseProject/TCACoordinators.plist
  Projects/App/Settings.bundle/LicenseProject/combine-schedulers.plist
  Projects/App/Settings.bundle/LicenseProject/kakao-ios-sdk.plist
  Projects/App/Settings.bundle/LicenseProject/lottie-ios.plist
  Projects/App/Settings.bundle/LicenseProject/swift-case-paths.plist
  Projects/App/Settings.bundle/LicenseProject/swift-clocks.plist
  Projects/App/Settings.bundle/LicenseProject/swift-collections.plist
  Projects/App/Settings.bundle/LicenseProject/swift-composable-architecture.plist
  Projects/App/Settings.bundle/LicenseProject/swift-concurrency-extras.plist
  Projects/App/Settings.bundle/LicenseProject/swift-custom-dump.plist
  Projects/App/Settings.bundle/LicenseProject/swift-dependencies.plist
  Projects/App/Settings.bundle/LicenseProject/swift-identified-collections.plist
  Projects/App/Settings.bundle/LicenseProject/swift-perception.plist
  Projects/App/Settings.bundle/LicenseProject/swift-syntax.plist
  Projects/App/Settings.bundle/LicenseProject/swiftui-navigation.plist
  Projects/App/Settings.bundle/LicenseProject/xctest-dynamic-overlay.plist
  Projects/App/Settings.bundle/Root.plist
Labels: Infra

#59 [Feat] KakaoAPIClient, KeyChainClient, KakaoLoginView, KakaoLoginErrorToast 뷰 생성
  Projects/App/Info.plist
  Projects/App/Project.swift
  Projects/App/Sources/AppDelegateCore.swift
  Projects/App/Sources/GabbangzipApp.swift
  Projects/App/Sources/RootCore.swift
  Projects/App/Sources/RootView.swift
  Projects/Core/Models/APIError/APIErrorResponse.swift
  Projects/Core/Models/Kakao/DTO/KaKaoUserInformation.swift
  Projects/Core/Models/Kakao/DTO/KakaoToken.swift
  Projects/Core/Models/Kakao/Request/KakaoLoginRequestInformation.swift
  Projects/Core/Models/Kakao/Response/KakaoResponse.swift
  Projects/Core/Models/Kakao/Response/PICUserInformation.swift
  Projects/Core/Services/GetHelpers/GabbangzipAPIClientDelegate.swift
  Projects/Core/Services/GetHelpers/NetworkManager.swift
  Projects/Core/Services/KakaoAPI/KakaoAPI.swift
  Projects/Core/Services/KakaoAPI/KakaoAPIClient.swift
  Projects/Core/Services/KakaoLogin/KakaoLoginClient.swift
  Projects/Core/Services/KeyChain/KeyChainClient.swift
  Projects/Core/Services/UserNotifications/UserNotificationClient.swift
  Projects/DesignSystem/Resources/Icons.xcassets/Login/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Login/kakao.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Login/kakao.imageset/kakao.png
  Projects/DesignSystem/Resources/Icons.xcassets/Login/kakao.imageset/kakao@2x.png
  Projects/DesignSystem/Resources/Icons.xcassets/Login/kakao.imageset/kakao@3x.png
  Projects/DesignSystem/Resources/Icons.xcassets/Login/picLogo.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Login/picLogo.imageset/picLogo.png
  Projects/DesignSystem/Resources/Icons.xcassets/Login/picLogo.imageset/picLogo@2x.png
  Projects/DesignSystem/Resources/Icons.xcassets/Login/picLogo.imageset/picLogo@3x.png
  Projects/DesignSystem/Resources/Lotties/login.json
  Projects/DesignSystem/Sources/Views/Lottie/LottieView.swift
  Projects/Features/Coordinator/Project.swift
  Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginCore.swift
  Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
  Projects/Features/Scene/KakaoLoginScene/KakaoLogin/ToastView.swift
  Projects/Features/Scene/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+extensions.swift
  Tuist/ResourceSynthesizers/Fonts.stencil
Labels: Feature

#66 [Design] Toast / Popup 컴포넌트 추가
  Projects/DesignSystem/Sources/Views/Popup/PopupView.swift
  Projects/DesignSystem/Sources/Views/Popup/PopupViewModifier.swift
  Projects/DesignSystem/Sources/Views/Toast/ToastModifier.swift
  Projects/DesignSystem/Sources/Views/Toast/ToastType.swift
  Projects/DesignSystem/Sources/Views/Toast/ToastView.swift
Labels: Design
