Repository mash-up-kr/gabbangzip-iOS, pull requests merged in 2024-09, with the labels that each got.

#137 [Feat] 홈 화면의 플로팅 버튼 비활성화 기능 추가 및 User아이콘 에셋 교체
  Projects/DesignSystem/Resources/Icons.xcassets/Navigation/user.imageset/user.svg
  Projects/Features/Scene/MainScene/Home/HomeCore.swift
  Projects/Features/Scene/MainScene/Home/HomeView.swift
Labels: Feature, Design

#138 [Fix] 그룹 상세 수정 사항 반영
  Projects/DesignSystem/Sources/Views/NavigationBar/NavigationBar.swift
  Projects/DesignSystem/Sources/Views/NavigationBar/Types/NavigationBarType.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventCompletedView/EventCompletedView.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventContainerView.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventDefaultView/EventDefaultView.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailCore.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
Labels: Bugfix

#140 [Fix] 자잘한 디자인 수정
  Projects/Core/Models/Group/Response/MemberList.swift
  Projects/Features/Scene/GroupDetailScene/MemberList/MemberListCore.swift
  Projects/Features/Scene/Lovebug/GroupDataStatus+extensions.swift
  Projects/Features/Scene/MainScene/GetStartedView/GetStartedView.swift
  Projects/Features/Scene/MainScene/Group/Views/GroupContentView.swift
  Projects/Features/Scene/MainScene/Home/Views/FloatingButton.swift
Labels: Design

#144 [Hotfix] 이벤트 생성 부분 이미지 업로드 로직 개선 및 날짜 컴포넌트 제거
  Projects/App/Info.plist
  Projects/Features/Scene/CreateEventScene/CreateEventCore.swift
  Projects/Features/Scene/CreateEventScene/CreateEventView.swift
Labels: Hotfix

#146 [Fix] Group in 에셋 교체
  Projects/DesignSystem/Resources/Icons.xcassets/Common/group_in.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Common/group_in.imageset/group_in.pdf
  Projects/DesignSystem/Resources/Icons.xcassets/Common/group_in.imageset/group_in.svg
Labels: Design

#152 [Hotfix] 그룹 코드 복사 양식 수정
  Projects/Features/Scene/CreateGroupScene/CreateGroupCompletion/CreateGroupCompletionCore.swift
  Projects/Features/Scene/GroupDetailScene/MemberList/MemberListCore.swift
Labels: Hotfix

#155 design: 프레임에 흰색 placeholder 추가
  Projects/Features/Scene/Lovebug/PhotoWithFrame.swift
Labels: Design

#156 [Hotfix] 그룹 생성 시 사진 업로드 동안 인디케이터 노출
  Projects/Features/Scene/CreateGroupScene/SelectGroupPhoto/SelectGroupPhotoCore.swift
  Projects/Features/Scene/CreateGroupScene/SelectGroupPhoto/SelectGroupPhotoView.swift
Labels: Hotfix

#159 [Feat] 2열 그리드 화면 구현
  Projects/DesignSystem/Resources/Icons.xcassets/Common/grid.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Common/grid.imageset/grid.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Common/list.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Common/list.imageset/list.svg
  Projects/Features/Scene/MainScene/Home/GroupGrid/GroupGridCore.swift
  Projects/Features/Scene/MainScene/Home/GroupGrid/GroupGridView.swift
  Projects/Features/Scene/MainScene/Home/GroupGridItem/GroupGridItemCore.swift
  Projects/Features/Scene/MainScene/Home/GroupGridItem/GroupGridItemView.swift
  Projects/Features/Scene/MainScene/Home/GroupList/GroupListCore.swift
  Projects/Features/Scene/MainScene/Home/GroupList/GroupListView.swift
  Projects/Features/Scene/MainScene/Home/HomeCore.swift
  Projects/Features/Scene/MainScene/Home/HomeView.swift
Labels: Feature

#162 [Hotfix] 홈 화면의 버튼이 작동하지 않는 이슈 해결
  Projects/Features/Scene/MainScene/Home/GroupGrid/GroupGridCore.swift
  Projects/Features/Scene/MainScene/Home/GroupList/GroupListCore.swift
Labels: Hotfix

#160 [Feat] 이벤트 생성 시 DatePicker로 날짜 선택
  Projects/DesignSystem/Sources/Views/Date/GabbangzipDate.swift
  Projects/Features/Scene/CreateEventScene/CreateEventCore.swift
  Projects/Features/Scene/CreateEventScene/CreateEventView.swift
Labels: Feature
