Repository mash-up-kr/gabbangzip-iOS, pull requests merged in 2024-08, with the labels that each got.

#95 [Feature] 그룹 들어가기 구현
  Projects/Features/Scene/MainScene/JoinGroup/JoinGroupCore.swift
  Projects/Features/Scene/MainScene/JoinGroup/JoinGroupView.swift
  Xcode Templates/Feature.xctemplate/___FILEBASENAME___Core.swift
Labels: Feature

#98 [Feat] 그룹 만들기2
  Projects/App/Info.plist
  Projects/Core/Models/CreateGroup/Response/CreatedGroupInfo.swift
  Projects/Core/Models/CreateGroup/Response/FileUploadInfo.swift
  Projects/Core/Project.swift
  Projects/Core/Services/PicAPIClients/CreateGroupAPI/CreateGroupAPI.swift
  Projects/Core/Services/PicAPIClients/CreateGroupAPI/CreateGroupAPIClient.swift
  Projects/Core/Services/PicAPIClients/FileUploadAPI/FileUploadAPI.swift
  Projects/Core/Services/PicAPIClients/FileUploadAPI/FileUploadAPIClient.swift
  Projects/Core/Services/UIPasteBoard/UIPasteBoardClient.swift
  Projects/DesignSystem/Sources/Views/Button/SmallButton.swift
  Projects/DesignSystem/Sources/Views/PhotoPicker/DataURL.swift
  Projects/DesignSystem/Sources/Views/PhotoPicker/GabbangzipPhotoPicker.swift
  Projects/DesignSystem/Sources/Views/PhotoPicker/PhotoInfo.swift
  Projects/Features/Coordinator/CreateGroupCoordinator/CreateGroupCoordinatorCore.swift
  Projects/Features/Coordinator/CreateGroupCoordinator/CreateGroupCoordinatorView.swift
  Projects/Features/Coordinator/CreateGroupCoordinator/CreateGroupScreen.swift
  Projects/Features/Coordinator/MainCoordinator/MainCoordinatorCore.swift
  Projects/Features/Scene/CreateGroupScene/CreateGroupCompletion/CreateGroupCompletionCore.swift
  Projects/Features/Scene/CreateGroupScene/CreateGroupCompletion/CreateGroupCompletionView.swift
  Projects/Features/Scene/CreateGroupScene/Extensions/Keyword+extensions.swift
  Projects/Features/Scene/CreateGroupScene/SelectGroupPhoto/SelectGroupPhotoCore.swift
  Projects/Features/Scene/CreateGroupScene/SelectGroupPhoto/SelectGroupPhotoView.swift
  Projects/Features/Scene/CreateGroupScene/SelectKeyword/SelectKeywordCore.swift
  Projects/Features/Scene/CreateGroupScene/SetGroupName/SetGroupNameCore.swift
  Projects/Features/Scene/GroupDetailScene/MemberList/MemberListCore.swift
  Projects/Features/Scene/MainScene/GroupList/GroupListCore.swift
  Projects/Features/Scene/MainScene/GroupList/GroupListView.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+extensions.swift
Labels: Feature

#96 [Feat] FCM 구현
  .gitignore
  Gemfile.lock
  Projects/App/Info.plist
  Projects/App/Project.swift
  Projects/App/Resources/Development/Dev-Gabbangzip.entitlements
  Projects/App/Resources/Product/Prod-Gabbangzip.entitlements
  Projects/App/Sources/AppDelegate.swift
  Projects/App/Sources/AppDelegateCore.swift
  Projects/Core/Project.swift
  Projects/Core/Services/Bundle/BundleClient.swift
  Projects/Core/Services/Firebase/FirebaseClient.swift
  Projects/Core/Services/UIApplication/UIApplicationClient.swift
  Projects/Core/Services/UserNotifications/UserNotificationClient.swift
  Tuist/Package.resolved
  Tuist/Package.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+extensions.swift
Labels: Feature

#105 [Feat] 추가하기 버튼 및 화면 전환 구현, 그룹 참가 API 연동, 이미지 비율 변경, 홈 화면 갱신 구현
  Projects/Core/Common/Extensions/UINavigationController+extensions.swift
  Projects/Core/Models/Group/Response/GroupData.swift
  Projects/Core/Models/Group/Response/GroupID.swift
  Projects/Core/Models/Group/Response/GroupsData.swift
  Projects/Core/Services/PicAPIClients/GroupAPI/GroupAPI.swift
  Projects/Core/Services/PicAPIClients/GroupAPI/GroupAPIClient.swift
  Projects/DesignSystem/Resources/Icons.xcassets/Common/group_in.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Common/group_in.imageset/group_in.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Common/group_plus.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Common/group_plus.imageset/group_plus.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Common/plus_template.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Common/plus_template.imageset/plus_template.svg
  Projects/DesignSystem/Sources/Views/NavigationBar/NavigationBar.swift
  Projects/DesignSystem/Sources/Views/NavigationBar/Types/NavigationBarType.swift
  Projects/DesignSystem/Sources/Views/PlaygroundView.swift
  Projects/Features/Coordinator/CreateGroupCoordinator/CreateGroupCoordinatorView.swift
  Projects/Features/Coordinator/MainCoordinator/MainCoordinatorCore.swift
  Projects/Features/Coordinator/MainCoordinator/MainCoordinatorView.swift
  Projects/Features/Coordinator/MainCoordinator/MainScreen.swift
  Projects/Features/Scene/CreateGroupScene/CreateGroupCompletion/CreateGroupCompletionView.swift
  Projects/Features/Scene/CreateGroupScene/SelectGroupPhoto/SelectGroupPhotoCore.swift
  Projects/Features/Scene/CreateGroupScene/SelectGroupPhoto/SelectGroupPhotoView.swift
  Projects/Features/Scene/MainScene/GroupList/GroupListCore.swift
  Projects/Features/Scene/MainScene/GroupList/GroupListView.swift
  Projects/Features/Scene/MainScene/GroupList/Views/FloatingButton.swift
  Projects/Features/Scene/MainScene/GroupList/Views/FloatingOptionButton.swift
  Projects/Features/Scene/MainScene/JoinGroup/JoinGroupCore.swift
  Projects/Features/Scene/MainScene/JoinGroup/JoinGroupView.swift
Labels: Bugfix, Feature, Design

#106 [Feature] 투표하기 API 연동
  Projects/Core/Models/Vote/Request/VoteReqDTO.swift
  Projects/Core/Models/Vote/Response/VoteCompleteInfo.swift
  Projects/Core/Models/Vote/Response/VoteOptionInfo.swift
  Projects/Core/Services/PicAPIClients/VoteAPI/VoteAPI.swift
  Projects/Core/Services/PicAPIClients/VoteAPI/VoteAPIClient.swift
  Projects/Core/Services/UserDefaults/UserDefaultsClient.swift
  Projects/DesignSystem/Project.swift
  Projects/DesignSystem/Resources/Images.xcassets/Vote/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Vote/voteGuideLeft.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Vote/voteGuideLeft.imageset/voteGuideLeft.svg
  Projects/DesignSystem/Resources/Images.xcassets/Vote/voteGuideRight.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/Vote/voteGuideRight.imageset/voteGuideRight.svg
  Projects/DesignSystem/Sources/Models/Keyword+extensions.swift
  Projects/DesignSystem/Sources/Views/PhotoWithFrame/PhotoWithFrame.swift
  Projects/Features/Scene/CreateGroupScene/CreateGroupCompletion/CreateGroupCompletionView.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventControlButton.swift
  Projects/Features/Scene/GroupDetailScene/MemberList/MemberListView.swift
  Projects/Features/Scene/GroupDetailScene/Vote/Vote/VoteButton/VoteButton.swift
  Projects/Features/Scene/GroupDetailScene/Vote/Vote/VoteCore.swift
  Projects/Features/Scene/GroupDetailScene/Vote/Vote/VoteGuideView/VoteGuideView.swift
  Projects/Features/Scene/GroupDetailScene/Vote/Vote/VoteSwipeView/VoteSwipeView.swift
  Projects/Features/Scene/GroupDetailScene/Vote/Vote/VoteView.swift
  Projects/Features/Scene/GroupDetailScene/Vote/VoteComplete/VoteCompleteCore.swift
  Projects/Features/Scene/GroupDetailScene/Vote/VoteComplete/VoteCompleteView.swift
  Projects/Features/Scene/GroupDetailScene/Vote/VoteCore.swift
Labels: Feature

#108 [Hotfix] 로그아웃 로직 수정, LaunchingView 삭제, MyPage onAppear구현, MyPage Coordinator 수정, FirebaseClient 수정
  Projects/App/Sources/AppDelegateCore.swift
  Projects/App/Sources/RootCore.swift
  Projects/App/Sources/RootView.swift
  Projects/Core/Services/Firebase/FirebaseClient.swift
  Projects/Core/Services/KakaoLogin/KakaoLoginClient.swift
  Projects/Features/Coordinator/MainCoordinator/MainCoordinatorCore.swift
  Projects/Features/Coordinator/MainCoordinator/MainCoordinatorView.swift
  Projects/Features/Coordinator/MainCoordinator/MainScreen.swift
  Projects/Features/Coordinator/MyPageCoordinator/MyPageCoordinatorCore.swift
  Projects/Features/Coordinator/MyPageCoordinator/MyPageCoordinatorView.swift
  Projects/Features/Coordinator/MyPageCoordinator/MyPageScreen.swift
  Projects/Features/Coordinator/Project.swift
  Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
  Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+extensions.swift
Labels: Hotfix

#112 [Feat] 홈 화면 리팩토링 및 API연동
  Projects/Core/Models/Group/Response/GroupData.swift
  Projects/Core/Models/Group/Response/GroupsData.swift
  Projects/Core/Models/PushNotification/Response/KookInfo.swift
  Projects/Core/Models/PushNotification/Response/RegisteredFCMToken.swift
  Projects/Core/Services/PicAPIClients/PushNotificationAPI/PushNotificationAPI.swift
  Projects/Core/Services/PicAPIClients/PushNotificationAPI/PushNotificationAPIClient.swift
  Projects/DesignSystem/Sources/Views/Toast/ToastType.swift
  Projects/Features/Scene/CreateGroupScene/CreateGroupCompletion/CreateGroupCompletionView.swift
  Projects/Features/Scene/CreateGroupScene/SelectGroupPhoto/SelectGroupPhotoCore.swift
  Projects/Features/Scene/GroupDetailScene/Vote/VoteComplete/VoteCompleteView.swift
  Projects/Features/Scene/Lovebug/Frame+extensions.swift
  Projects/Features/Scene/Lovebug/GroupDataStatus+extensions.swift
  Projects/Features/Scene/Lovebug/Keyword+extensions.swift
  Projects/Features/Scene/Lovebug/PhotoWithFrame.swift
  Projects/Features/Scene/MainScene/Group/GroupCore.swift
  Projects/Features/Scene/MainScene/Group/GroupView.swift
  Projects/Features/Scene/MainScene/Group/Views/GroupContentView.swift
  Projects/Features/Scene/MainScene/Group/Views/GroupHeaderView.swift
  Projects/Features/Scene/MainScene/Group/Views/PhotoCardBackView.swift
  Projects/Features/Scene/MainScene/Group/Views/PhotoCardFrontView.swift
  Projects/Features/Scene/MainScene/GroupList/GroupListCore.swift
  Projects/Features/Scene/MainScene/GroupList/GroupListView.swift
  Projects/Features/Scene/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+extensions.swift
Labels: Refactoring, Feature

#109 [Feat] 멤버 리스트 API 연동
  Projects/Core/Models/Group/Response/MemberList.swift
  Projects/Core/Models/GroupDetail/MemberList.swift
  Projects/Core/Services/PicAPIClients/GroupAPI/GroupAPI.swift
  Projects/Core/Services/PicAPIClients/GroupAPI/GroupAPIClient.swift
  Projects/DesignSystem/Sources/Views/Button/SmallButton.swift
  Projects/Features/Scene/GroupDetailScene/MemberList/MemberListCore.swift
  Projects/Features/Scene/GroupDetailScene/MemberList/MemberListView.swift
  Projects/Features/Scene/GroupDetailScene/MemberList/MemberView/MemberView.swift
Labels: Feature

#119 [Feat] 그룹 상세 API 연동 1탄
  Projects/Core/Models/Event/Response/EventVisitInfo.swift
  Projects/Core/Models/Group/Response/CardBackImage.swift
  Projects/Core/Models/Group/Response/GroupData.swift
  Projects/Core/Models/Group/Response/GroupDetailInfo.swift
  Projects/Core/Models/GroupDetail/EventDetail.swift
  Projects/Core/Models/GroupDetail/EventItemInfo.swift
  Projects/Core/Models/GroupDetail/GroupCategory.swift
  Projects/Core/Models/GroupDetail/GroupDetail.swift
  Projects/Core/Services/PicAPIClients/EventAPI/EventAPI.swift
  Projects/Core/Services/PicAPIClients/EventAPI/EventAPIClient.swift
  Projects/Core/Services/PicAPIClients/GroupAPI/GroupAPI.swift
  Projects/Core/Services/PicAPIClients/GroupAPI/GroupAPIClient.swift
  Projects/DesignSystem/Resources/Icons.xcassets/Common/share.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons.xcassets/Common/share.imageset/Group 5024.svg
  Projects/DesignSystem/Resources/Icons.xcassets/Common/share.imageset/share.svg
  Projects/DesignSystem/Sources/Views/PhotoWithFrame/PhotoWithFrame.swift
  Projects/Features/Scene/CreateGroupScene/CreateGroupCompletion/CreateGroupCompletionView.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventCompletedView/EventCompletedView.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventCompletedView/Views/ShareButton.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventContainerView.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventControlButton.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventProgressView.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventProgressView/EventProgressView.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/EventGrid/EventItemView.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailCore.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/HistoryGrid/HistoryGridView.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/HistoryGrid/HistoryItemView.swift
  Projects/Features/Scene/GroupDetailScene/HistoryDetail/HistoryDetailCore.swift
  Projects/Features/Scene/GroupDetailScene/HistoryDetail/HistoryDetailView.swift
  Projects/Features/Scene/GroupDetailScene/Vote/VoteComplete/VoteCompleteView.swift
  Projects/Features/Scene/Lovebug/PhotoCardBackView.swift
  Projects/Features/Scene/Lovebug/PhotoWithFrame.swift
  Projects/Features/Scene/MainScene/Group/Views/GroupContentView.swift
Labels: Feature

#121 [Feat] 그룹 상세 API 연동 2탄
  Projects/Core/Models/Group/Response/GroupDetailInfo.swift
  Projects/Core/Models/Vote/Response/VoteCompleteInfo.swift
  Projects/Features/Coordinator/GroupDetailCoordinator/GroupDetailCoordinatorCore.swift
  Projects/Features/Coordinator/GroupDetailCoordinator/GroupDetailCoordinatorView.swift
  Projects/Features/Coordinator/GroupDetailCoordinator/GroupDetailScreen.swift
  Projects/Features/Coordinator/MainCoordinator/MainCoordinatorCore.swift
  Projects/Features/Coordinator/MainCoordinator/MainCoordinatorView.swift
  Projects/Features/Coordinator/MainCoordinator/MainScreen.swift
  Projects/Features/Coordinator/Project.swift
  Projects/Features/Scene/CreateGroupScene/CreateGroupCompletion/CreateGroupCompletionView.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventCompletedView/EventCompletedView.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventContainerView.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailCore.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/HistoryGrid/HistoryGridView.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/HistoryGrid/HistoryItemView.swift
  Projects/Features/Scene/GroupDetailScene/HistoryDetail/HistoryDetailCore.swift
  Projects/Features/Scene/GroupDetailScene/HistoryDetail/HistoryDetailView.swift
  Projects/Features/Scene/GroupDetailScene/MemberList/MemberListCore.swift
  Projects/Features/Scene/GroupDetailScene/MemberList/MemberListView.swift
  Projects/Features/Scene/GroupDetailScene/Vote/Vote/VoteCore.swift
  Projects/Features/Scene/GroupDetailScene/Vote/VoteComplete/VoteCompleteCore.swift
  Projects/Features/Scene/GroupDetailScene/Vote/VoteComplete/VoteCompleteView.swift
  Projects/Features/Scene/MainScene/Group/GroupCore.swift
  Projects/Features/Scene/MainScene/GroupList/GroupListCore.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+extensions.swift
Labels: Feature

#123 [Fix] GroupList 이름 변경 및 Response 오타 수정
  Projects/App/Sources/RootCore.swift
  Projects/Core/Models/PushNotification/Response/RegisteredFCMToken.swift
  Projects/Features/Coordinator/MainCoordinator/MainCoordinatorCore.swift
  Projects/Features/Coordinator/MainCoordinator/MainCoordinatorView.swift
  Projects/Features/Coordinator/MainCoordinator/MainScreen.swift
  Projects/Features/Scene/CreateGroupScene/SelectGroupPhoto/SelectGroupPhotoCore.swift
  Projects/Features/Scene/MainScene/Home/HomeCore.swift
  Projects/Features/Scene/MainScene/Home/HomeView.swift
  Projects/Features/Scene/MainScene/Home/Views/FlipView.swift
  Projects/Features/Scene/MainScene/Home/Views/FloatingButton.swift
  Projects/Features/Scene/MainScene/Home/Views/FloatingOptionButton.swift
  Projects/Features/Scene/MainScene/JoinGroup/JoinGroupCore.swift
Labels: Chore

#126 [Fix] 어느 그룹에도 속하지 않은 사용자에게는 홈화면이 아닌 시작화면이 보여지도록 수정
  Projects/App/Sources/RootCore.swift
  Projects/Core/Common/Extensions/View+extensions.swift
  Projects/Core/Common/Views/DisableSwipeBackModifier.swift
  Projects/DesignSystem/Sources/Views/Button/GabbangzipButton.swift
  Projects/Features/Coordinator/CreateGroupCoordinator/CreateGroupCoordinatorCore.swift
  Projects/Features/Coordinator/CreateGroupCoordinator/CreateGroupCoordinatorView.swift
  Projects/Features/Coordinator/CreateGroupCoordinator/CreateGroupScreen.swift
  Projects/Features/Coordinator/MainCoordinator/MainCoordinatorCore.swift
  Projects/Features/Coordinator/MainCoordinator/MainCoordinatorView.swift
  Projects/Features/Coordinator/MainCoordinator/MainScreen.swift
  Projects/Features/Scene/CreateGroupScene/CreateGroupCompletion/CreateGroupCompletionCore.swift
  Projects/Features/Scene/CreateGroupScene/CreateGroupCompletion/CreateGroupCompletionView.swift
  Projects/Features/Scene/CreateGroupScene/SelectGroupPhoto/SelectGroupPhotoCore.swift
  Projects/Features/Scene/CreateGroupScene/SelectGroupPhoto/SelectGroupPhotoView.swift
  Projects/Features/Scene/CreateGroupScene/SelectKeyword/SelectKeywordCore.swift
  Projects/Features/Scene/CreateGroupScene/SelectKeyword/SelectKeywordView.swift
  Projects/Features/Scene/CreateGroupScene/SetGroupName/SetGroupNameCore.swift
  Projects/Features/Scene/CreateGroupScene/SetGroupName/SetGroupNameView.swift
  Projects/Features/Scene/LoginScene/Login/LoginCore.swift
  Projects/Features/Scene/MainScene/GetStartedView/GetStartedCore.swift
  Projects/Features/Scene/MainScene/GetStartedView/GetStartedView.swift
  Projects/Features/Scene/MainScene/Home/HomeView.swift
  Projects/Features/Scene/MainScene/JoinGroup/JoinGroupCore.swift
  Projects/Features/Scene/MainScene/JoinGroup/JoinGroupView.swift
Labels: Refactoring

#128 [Fix] 그룹 상세/이벤트 투표 관련 오류 수정
  Projects/App/Resources/Assets.xcassets/ProdAppIcon.appiconset/Contents.json
  Projects/App/Resources/Assets.xcassets/ProdAppIcon.appiconset/iOS App Icon.png
  Projects/App/Resources/Assets.xcassets/ProdAppIcon.appiconset/logo.png
  Projects/App/Sources/RootCore.swift
  Projects/Core/Common/Extensions/DateFormatter+extensions.swift
  Projects/Core/Common/Extensions/String+extensions.swift
  Projects/Core/Common/Views/ViewHeightKey.swift
  Projects/Core/Models/Event/Request/ImageUploadReqDTO.swift
  Projects/Core/Models/Event/Response/ImageUploadInfo.swift
  Projects/Core/Models/Group/Response/GroupDetailInfo.swift
  Projects/Core/Models/Vote/Response/VoteCompleteInfo.swift
  Projects/Core/Models/Vote/Response/VoteOptionInfo.swift
  Projects/Core/Services/GetHelpers/GabbangzipAPIClientDelegate.swift
  Projects/Core/Services/PicAPIClients/EventAPI/EventAPI.swift
  Projects/Core/Services/PicAPIClients/EventAPI/EventAPIClient.swift
  Projects/Core/Services/PicAPIClients/GroupAPI/GroupAPI.swift
  Projects/Core/Services/PicAPIClients/VoteAPI/VoteAPIClient.swift
  Projects/DesignSystem/Sources/Views/PhotoPicker/DataURL.swift
  Projects/DesignSystem/Sources/Views/PhotoPicker/GabbangzipPhotoPicker.swift
  Projects/DesignSystem/Sources/Views/PhotoPicker/MaxSelectedCountType.swift
  Projects/Features/Coordinator/GroupDetailCoordinator/GroupDetailCoordinatorCore.swift
  Projects/Features/Coordinator/MainCoordinator/MainCoordinatorCore.swift
  Projects/Features/Scene/CreateEventScene/CreateEventCore.swift
  Projects/Features/Scene/CreateEventScene/CreateEventView.swift
  Projects/Features/Scene/CreateGroupScene/SelectGroupPhoto/SelectGroupPhotoCore.swift
  Projects/Features/Scene/CreateGroupScene/SelectGroupPhoto/SelectGroupPhotoView.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventCompletedView/EventCompletedView.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventContainerView.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventProgressView/EventProgressView.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailCore.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/HistoryGrid/HistoryGridView.swift
  Projects/Features/Scene/GroupDetailScene/GroupDetail/Views/CustomBottomSheetView.swift
  Projects/Features/Scene/GroupDetailScene/HistoryDetail/HistoryDetailCore.swift
  Projects/Features/Scene/GroupDetailScene/HistoryDetail/HistoryDetailView.swift
  Projects/Features/Scene/GroupDetailScene/MemberList/MemberListCore.swift
  Projects/Features/Scene/GroupDetailScene/MemberList/MemberListView.swift
  Projects/Features/Scene/GroupDetailScene/Vote/Vote/VoteCore.swift
  Projects/Features/Scene/GroupDetailScene/Vote/Vote/VoteSwipeView/VoteSwipeView.swift
  Projects/Features/Scene/GroupDetailScene/Vote/Vote/VoteView.swift
  Projects/Features/Scene/GroupDetailScene/Vote/VoteComplete/VoteCompleteCore.swift
  Projects/Features/Scene/GroupDetailScene/Vote/VoteComplete/VoteCompleteView.swift
  Projects/Features/Scene/Lovebug/GroupDataStatus+extensions.swift
  Projects/Features/Scene/MainScene/Group/GroupCore.swift
  Projects/Features/Scene/MainScene/Group/GroupView.swift
  Projects/Features/Scene/MainScene/Group/Views/GroupContentView.swift
  Projects/Features/Scene/MainScene/Home/HomeCore.swift
  Projects/Features/Scene/MainScene/JoinGroup/JoinGroupView.swift
Labels: Bugfix
