Repository mash-up-kr/gabbangzip-iOS, pull requests merged in 2024-10, with the labels that each got.

#171 [Fix] 날짜 데이터 변환 타입 수정
  Projects/Core/Common/Extensions/DateFormatter+extensions.swift
Labels: Bugfix

#170 [Feat] 온보딩 페이지
  Projects/App/Sources/RootCore.swift
  Projects/App/Sources/RootView.swift
  Projects/Core/Services/Sources/KeyChain/KeyChainClient.swift
  Projects/DesignSystem/Project.swift
  Projects/DesignSystem/Resources/Images.xcassets/App/appExplanation1.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/App/appExplanation1.imageset/appExplanation1.png
  Projects/DesignSystem/Resources/Images.xcassets/App/appExplanation10.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/App/appExplanation10.imageset/appExplanation10.png
  Projects/DesignSystem/Resources/Images.xcassets/App/appExplanation11.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/App/appExplanation11.imageset/appExplanation11.png
  Projects/DesignSystem/Resources/Images.xcassets/App/appExplanation2.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/App/appExplanation2.imageset/appExplanation2.png
  Projects/DesignSystem/Resources/Images.xcassets/App/appExplanation3.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/App/appExplanation3.imageset/appExplanation3.png
  Projects/DesignSystem/Resources/Images.xcassets/App/appExplanation4.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/App/appExplanation4.imageset/appExplanation4.png
  Projects/DesignSystem/Resources/Images.xcassets/App/appExplanation5.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/App/appExplanation5.imageset/appExplanation5.png
  Projects/DesignSystem/Resources/Images.xcassets/App/appExplanation6.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/App/appExplanation6.imageset/appExplanation6.png
  Projects/DesignSystem/Resources/Images.xcassets/App/appExplanation7.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/App/appExplanation7.imageset/appExplanation7.png
  Projects/DesignSystem/Resources/Images.xcassets/App/appExplanation8.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/App/appExplanation8.imageset/appExplanation8.png
  Projects/DesignSystem/Resources/Images.xcassets/App/appExplanation9.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/App/appExplanation9.imageset/appExplanation9.png
  Projects/DesignSystem/Resources/Images.xcassets/App/onboarding01.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/App/onboarding01.imageset/onboarding01 1x.png
  Projects/DesignSystem/Resources/Images.xcassets/App/onboarding01.imageset/onboarding01 2x.png
  Projects/DesignSystem/Resources/Images.xcassets/App/onboarding01.imageset/onboarding01 3x.png
  Projects/DesignSystem/Resources/Images.xcassets/App/onboarding02.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/App/onboarding02.imageset/onboarding02 1x.png
  Projects/DesignSystem/Resources/Images.xcassets/App/onboarding02.imageset/onboarding02 2x.png
  Projects/DesignSystem/Resources/Images.xcassets/App/onboarding02.imageset/onboarding02 3x.png
  Projects/DesignSystem/Resources/Images.xcassets/App/onboarding03.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/App/onboarding03.imageset/onboarding03 1x.png
  Projects/DesignSystem/Resources/Images.xcassets/App/onboarding03.imageset/onboarding03 2x.png
  Projects/DesignSystem/Resources/Images.xcassets/App/onboarding03.imageset/onboarding03 3x.png
  Projects/DesignSystem/Resources/Images.xcassets/App/onboarding04.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/App/onboarding04.imageset/onboarding04 1x.png
  Projects/DesignSystem/Resources/Images.xcassets/App/onboarding04.imageset/onboarding04 2x.png
  Projects/DesignSystem/Resources/Images.xcassets/App/onboarding04.imageset/onboarding04 3x.png
  Projects/Features/Coordinator/Project.swift
  Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
  Projects/Features/Scene/OnboardingScene/Onboarding/OnboardingCore.swift
  Projects/Features/Scene/OnboardingScene/Onboarding/OnboardingView.swift
  Projects/Features/Scene/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+extensions.swift
  Workspace.swift
Labels: Feature

#172 [Fix] 공유 버튼 완료 시 disable되도록 수정
  Projects/Features/Scene/GroupDetailScene/HistoryDetail/HistoryDetailCore.swift
  Projects/Features/Scene/GroupDetailScene/HistoryDetail/HistoryDetailView.swift
Labels: Bugfix

#174 [Fix] 문구, 폰트, 크기, 아이콘 수정 및 로그아웃 버그 수정
  Projects/DesignSystem/Sources/Views/Chip/Tag.swift
  Projects/Features/Scene/CreateGroupScene/CreateGroupCompletion/CreateGroupCompletionView.swift
  Projects/Features/Scene/MainScene/Group/Views/PhotoCardFrontView.swift
  Projects/Features/Scene/MainScene/Home/GroupGrid/GroupGridView.swift
  Projects/Features/Scene/MainScene/Home/GroupGridItem/GroupGridItemView.swift
  Projects/Features/Scene/MainScene/Home/HomeView.swift
  Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
  Tuist/ResourceSynthesizers/Fonts.stencil
Labels: Bugfix, Design, Chore
